/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.seg;

public class App {
    public String getGreeting() {
        return "Vitor tem boca de veludo";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
